### PR TITLE
✏️ Documentation improvements

### PR DESCRIPTION
**Pull request by pgaspar**
## Description

Hey 👋 This is a first pass on the documentation language quality. I fixed a series of grammar issues and typos. I think I didn't break any links or change your original meaning too much, but please double check!

I'll see if I have time to help out with the other documentation files tomorrow 👍

Note: there's a lot of duplication in these docs. It may be difficult to keep all the documentation files consistent because of that. I ended up having to do a lot of search and replace to find all places where some sentences were being used. Not sure if there's a better approach here...

### Documentation

It's a documentation-only PR 📝

## Related Issues

None as far as I know.

### CODE REVIEW

**Comment by theowenyoung** [comment]
Thanks @pgaspar , Thanks for your great documentation job!

> there's a lot of duplication in these docs

Yes, for now `README.md`, `docs/index.md`, `packages/actionsflow/README.md` almost the same, I think they can all use `README.md` to instead. I'll add a script later, so that we only need to edit `README.md`

**Comment by theowenyoung** [comment]
Hey, @pgaspar , I have add a script for copy `README.md` to `packages/actionsflow/README.md` automatically when `README.md` changed.

But not for `index.md`, because there are some difference between index and readme, so we can only change it 2 times at every changes

**Comment by pgaspar** [comment]
@theowenyoung cool! I'll give the documentation another pass Monday 👍

**Comment by theowenyoung** [comment]
Thanks!

**Pull request merged**
